{
    "name": "Google Sheets Connector",
    "summary": "Realtime Odoo to Google Sheets sync with safe writeback and audit logs",
    "version": "18.0.1.0.0",
    "category": "Productivity",
    "author": "CoDE2",
    "license": "OPL-1",
    "depends": ["base", "web", "mail"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/niyu_sheets_queue.xml",
        "views/niyu_sheets_connection_views.xml",
        "views/niyu_sheets_mapping_views.xml",
        "views/niyu_sheets_log_views.xml",
        "data/ir_cron.xml",
        "views/niyu_sheets_menus.xml",
    ],
    "installable": True,
    "application": True,
    "price": 249.00,
    "currency": "USD",
    "images": ["static/description/banner.gif"],
}
